### PR TITLE
Add Sblack.app v1.0

### PR DESCRIPTION
**Pull request by michelegera**

### CODE REVIEW

**Comment by michelegera** [comment]
Hello,

Is there anything I should do to make the build pass and (hopefully) get the PR merged?

Thanks in advance!

**Comment by jonathantneal** [comment]
I was looking for this. Thanks for submitting it, @michelegera.

@vitorgalvao these links point to the official albeit walled build, which is why it was moved here from https://github.com/Homebrew/homebrew-cask/pull/55547

**Comment by vitorgalvao** [comment]
@jonathantneal I don’t manage this repo, @alebcay does.

**Comment by michelegera** [comment]
It seems that this repo has been abandoned, and Sblack [has been discontinued](https://www.sblack.online), so I’ll go ahead and close this PR.

**Pull request closed without merging**
