### PR TITLE
Add obs-ndi v4.5.3

### PR DESCRIPTION
**Pull request by coreygo**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission appears to be for [a vendorless build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].
  - The OBS-NDI plugin is via the [OBS Project forum] and respective [GitHub repository].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256
[OBS Project forum]: https://obsproject.com/forum/resources/obs-ndi-newtek-ndi™-integration-into-obs-studio.528/
[GitHub repository]: https://github.com/Palakis/obs-ndi/releases

### CODE REVIEW

**Comment by coreygo** [comment]
Greetings @vitorgalvao, apologize for pinging you but you're the top contributor here and since this pull request has been sitting…

I'm wondering:
- Is this the best repo?
- Is this even worthy of a merge?
- If so, can you initiate another Travis CI build check?

**Comment by vitorgalvao** [comment]
Aren’t these official builds?

**Comment by coreygo** [comment]
Thanks again for the assistance.

I assumed [alehouse/homebrew-unofficial](https://github.com/alehouse/homebrew-unofficial) was the place because while the .pkg has a Github repository, the plugin is distributed/supported via the OBS Project forum:

"Vendorless: A binary distributed without an official website, like a forum posting."

If that assumption was incorrect, I'm happy to resubmit to [Homebrew/homebrew-cask](https://github.com/Homebrew/homebrew-cask). Would certainly make things easier as I don't normally tap homebrew-unofficial. Imagine not as many do 😄

Doing another quick search of the web, it looks like NewTek has a [blog post here](https://www.newtek.com/blog/tips/using-obs-ndi-plugin/) which refers to the GitHub repository. If NDI had an official page specifically set up for OBS-NDI as they do for the NDI Tools and SDK I'd have originally submitted to homebrew-cask.

**Comment by vitorgalvao** [comment]
@coreygo This is (looks like?) an official release by the team on the official forums, so the case is a bit different. We could fit it in the main repos.

But we probably won’t, because this seems too obscure to me (as in, you’d be the only one using it). So I suggest you either consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for it, or if you want it in this repo, that’s @alebcay’s call. This repo is for stuff we thought didn’t belong *at all* in the official repos and would thus purge. @alebcay offered to maintain them, and that’s why it’s a sister project, i.e. it does not have official standing.

**Comment by coreygo** [comment]
@vitorgalvao gotcha. Thanks for the clarification. I also wonder about obscurity, it does have 90K+ downloads according to the forum but I'm not sure how many of those are MacOS+Homebrew+OBS users 😉 — (analytics?). I pinged Palakis on the forum to mention Homebrew installation but haven't heard back. I guess I'll close this and _maybe_ create my own tap.

**Pull request closed without merging**
